<?php
require_once __DIR__.'/../inc/auth.php';
?>
<!doctype html>
<html lang="fr">
<head>
  <meta charset="utf-8">
  <title>Dashboard - Resto</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="../assets/css/style.css">
</head>
<body class="bg-white">
  <nav class="navbar navbar-light bg-light">
    <div class="container">
      <a class="navbar-brand" href="/back-office/dashboard.php">Back-office</a>
      <div>
        <a class="btn btn-outline-secondary" href="/back-office/profile.php">Profile</a>
        <a class="btn btn-outline-danger" href="/logout.php">Déconnexion</a>
      </div>
    </div>
  </nav>

  <main class="container-fluid py-3">
    <div class="row mb-2">
      <div class="col-auto">
        <label class="form-label">Zone</label>
        <select id="zoneSelect" class="form-select"></select>
      </div>
      <div class="col-auto">
        <label class="form-label">Période</label>
        <select id="periodSelect" class="form-select"></select>
      </div>
    </div>

    <div class="table-responsive" style="height:70vh; overflow:auto; border:1px solid #e9ecef;">
      <table id="mealsTable" class="table table-sm table-bordered m-0" style="min-width:900px;">
        <!-- generated by JS -->
      </table>
    </div>
  </main>

<script src="../assets/js/dashboard.js"></script>
</body>
</html>
